Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Shared SSH key for password-less access
  config.ssh.insert_key = true

  ###############################
  #     SERVER (Controller)     #
  ###############################
  config.vm.define "alycgautS" do |srv|
    srv.vm.hostname = "alycgautS"
    srv.vm.network "private_network", ip: "192.168.56.110"

    srv.vm.provider "virtualbox" do |vb|
      vb.name = "alycgautS"
      vb.cpus = 2
      vb.memory = 1024
    end

    # Install K3s server
    srv.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --node-ip 192.168.56.110" sh -
      sudo snap install kubectl --classic
      sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/node-token.txt
    SHELL
  end

  ###############################
  #   SERVER WORKER (Agent)     #
  ###############################
  config.vm.define "alycgautSW" do |worker|
    worker.vm.hostname = "alycgautSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "alycgautSW"
      vb.cpus = 1
      vb.memory = 1024
    end

    # Install K3s agent
    worker.vm.provision "shell", inline: <<-SHELL
      export SERVER_IP="192.168.56.110"
      TOKEN=$(cat /vagrant/node-token.txt)

      curl -sfL https://get.k3s.io | \
        K3S_URL="https://${SERVER_IP}:6443" \
        K3S_TOKEN="${TOKEN}" \
        INSTALL_K3S_EXEC="agent --node-ip 192.168.56.111" \
        sh -

      sudo snap install kubectl --classic
    SHELL
  end
end
